README.md
Travis-ci image was removed because it was wrongly reporting this
project as failing. It will no longer be the case with this commit
because I have added ?branch=master te be sure the picture shows the
status of the master branch.
This reverts commit c60749c2491b04b29f0ac680f8b72f04a1f86a76.
=> Re-Add Travis image, but only for master branch

src/main/java/org/mariadb/jdbc/internal/common/AbstractValueObject.java
Resolved an issue where several concurrent reads of large byte arrays from a result set could cause threads to back up in a synchronization queue.
Calling #getBytes(...) on the result set makes a call to  #getValueObject(...), which calls AbstractValueObject#isNull(). The existing workflow was as follows:
1) Declare 'rawValue' and set it to the return value of #getString() <- This can cause issues as described below
2) Declare 'zeroTimestamp' and set it
3) Declare 'zeroDate' and set it
4.1) If 'rawBytes' is null, return true
4.2) If the datatype is either TIMESTAMP or DATETIME, check for equality between 'rawValue' and 'zeroTimestamp'. If true, return true
4.3) If the datatype is DATE, check for equality between 'rawValue' and 'zeroDate'. If true, return true
4.4) Otherwise, return false …
=> Removed Sometimes Unnecessary String Instantiation That Can Cause Thread Blocking

.travis/before_test.sh
This commit updates the Travis build script to use the DO NYC mirror. It fixes the transient CI build errors that were happening when trying to install the MariaDB server prior to running the driver tests.
FYI, I got the mirror URL from the MariaDB website: https://downloads.mariadb.org/mariadb/repositories/
This patch also adds a newline at the end of the script as it was missing.
=> Update apt repo in travis setup script

src/main/java/org/mariadb/jdbc/internal/common/DefaultOptions.java, src/main/java/org/mariadb/jdbc/internal/common/Options.java, src/main/java/org/mariadb/jdbc/internal/mysql/MySQLProtocol.java, src/test/java/org/mariadb/jdbc/LocalInfileDisableTest.java
This PR is split out into four separate commits:
1. Change `MySQLConnection.getProtocol()` method scope to "public". 
- This allows using it to issue a query cancellation.
2. Add a new option `allowLocalInfile` defaulting to "true"
- When disabled (*i.e. set to `false`*) it throws an error if a `... LOCAL INFILE ...` query is executed without first specifying an InputStream for it. This prevents a query from specifying an arbitrary file path via a URL syntax.
- The default is set to "true" so that the existing behavior is preserved (i.e. no compatibility issue).
3. Change SSLSocketFactory to set `autoClose` to true when creating the SSLSocket
- This fixes SSL connections from hanging when they're closed.
- See this [JDK bug](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6932592) for …
=> getProtocol() scope, LOCAL INFILE option, SSL fix, and SSL Cert Enhancement

pom.xml, src/test/java/org/mariadb/jdbc/ConnectionPoolTest.java
The first commit changes the scope of the DBCP dependency to "test" as it's only used in the tests. The second removes an out of date comment regarding adding the DBCP dependency to the pom to run the tests.
This isn't a breaking change from a functionality perspective as the driver itself hasn't changed at all. It may break downstream apps that are relying on the transitive dependency for DBCP. That's wrong on their part though so I don't think it's a real issue. Anybody who runs into that will see the error at compile time and will need to update their pom to explicitly include DBCP themselves.
Might want to add a line like that to the release notes for the next release of the driver.
=> Change Apache DBCP scope to test in pom

.travis/before_test.sh, .travis/gen-ssl.sh, src/main/java/org/mariadb/jdbc/internal/mysql/MySQLProtocol.java, src/test/java/org/mariadb/jdbc/DriverTest.java, src/test/java/org/mariadb/jdbc/SSLValidationTest.java
This patch fixes the Travis-CI server setup to configure SSL for the server versions that are tested. It also fixes some of the SSL tests so they run successfully (*the null password was breaking them*).
It's layered atop PR #31 (*as without that none of the trustServerCertificate tests would work*) and closes out #32.
=> Fix Travis-CI SSL

src/main/java/org/mariadb/jdbc/internal/mysql/MySQLProtocol.java, src/test/java/org/mariadb/jdbc/DriverTest.java
This fixes #30. See that issue for full details of what's broken and what this fixes.
It also includes a couple cosmetic fixes for removing unused SSL variables and the unused parameter of the `getSSLSocketFactory(...)` method. I've tested the fixed SSL option locally and it's working.
Unfortunately I haven't gotten the Travis test environment to actually run the SSL tests as the servers it tests against do not have SSL enabled. The Travis setup script will need to be modified to configure SSL and I haven't gotten around to that yet. Will probably submit it in a separate PR if nobody else gets around to it first.
=> Fix trustServerCertificate SSL Option

src/main/java/org/mariadb/jdbc/MySQLStatement.java, src/test/java/org/mariadb/jdbc/DriverTest.java
This pull request contains a fix for the getMoreResults method in MySQLStatement always returning true when there was a next result, instead of only returning true when the next result is a ResultSet. The related issue on Jira can be found here: https://mariadb.atlassian.net/browse/CONJ-179.
=> Fix Statement.getMoreResults() returning wrong value 

documentation/Failover-and-high-availability.md
As described in "Description" of "Failover / high availability options" section,
"retriesAllDown" means not seconds but the maximum number of connection attempts,
so I removed "seconds" from it.
=> Fix unit of default value of retriesAllDown in the documentation

src/main/java/org/mariadb/jdbc/internal/failover/AbstractMastersListener.java, src/main/java/org/mariadb/jdbc/internal/failover/AbstractMastersSlavesListener.java, src/main/java/org/mariadb/jdbc/internal/failover/impl/AuroraListener.java, src/main/java/org/mariadb/jdbc/internal/failover/impl/MastersFailoverListener.java, src/main/java/org/mariadb/jdbc/internal/failover/impl/MastersSlavesListener.java, src/main/java/org/mariadb/jdbc/internal/protocol/AuroraProtocol.java, src/main/java/org/mariadb/jdbc/internal/protocol/MasterProtocol.java, src/main/java/org/mariadb/jdbc/internal/protocol/MastersSlavesProtocol.java, src/test/java/org/mariadb/jdbc/failover/AuroraFailoverTest.java, src/test/java/org/mariadb/jdbc/failover/BaseReplication.java, src/test/java/org/mariadb/jdbc/failover/ReplicationFailoverTest.java, src/test/java/org/mariadb/jdbc/failover/SequentialFailoverTest.java
I have been discussing these issues and others with @rusher via email.  These are two issues which I have fixed in the fullcontact/mariadb-connector-j fork that do not depend on my threadly library, and thus are trivial to merge now.
I figured I would send these first because it's both trivial to separate out, and so I don't overload you guys with the next fix.
Check the commit messages for more details to each issue, and how they were fixed.
=> Fix blacklist race condition in AbstractMastersListener and sensitivity to system clock changes

src/main/java/org/mariadb/jdbc/internal/failover/thread/ConnectionValidator.java, src/main/java/org/mariadb/jdbc/internal/util/scheduler/FixedSizedSchedulerImpl.java, src/main/java/org/mariadb/jdbc/internal/util/scheduler/SchedulerServiceProviderHolder.java
I must have missed that in the fixed size case we were returning the implementation, rather than the interface.
Changing to the interface allows for easier extension and other scheduler implementations here.
=> SchedulerServiceProvider: Return interface rather than implementation

src/main/java/org/mariadb/jdbc/internal/failover/AbstractMastersListener.java, src/main/java/org/mariadb/jdbc/internal/failover/impl/MastersFailoverListener.java, src/main/java/org/mariadb/jdbc/internal/failover/impl/MastersSlavesListener.java
An AtomicBoolean does not provide a sufficent enough concurrency barrier here.
Instead I switched it to a volatile boolean + an Object that we synchronize on when the boolean is to be updated.
I am pretty sure I hit this today.  We are starting to use our aurora read replica more and more, so I am not unsurprised I might have uncovered this (or possibly another) race condition.  I had a condition where a connection, fresh from the pool (which I know had the read only state set back after it was done), complained as it tried to hit the read replica.
I hunted around for what might be the cause, and so far this is the only thing I have found.  If you have other ideas where this issue might be, please point me to where to look.
I will comment at the line where I believe the race condition …
=> MasterSlavesListener: Fix for race condition in switchReadOnlyConnection

src/main/java/org/mariadb/jdbc/MariaDbConnection.java
At the moment these methods do not use the RETURN_GENERATED_KEYS flag and thus when there is the attempt to read the generated keys this throws an exception.
prepareStatement(final String sql, final int[] columnIndexes)
prepareStatement(final String sql, final String[] columnNames)
... should use the RETURN_GENERATED_KEYS flag (and currently do not).
=> prepareStatement() taking column indexes or names should use Statement.RETURN_GENERATED_KEYS flag.

src/main/java/org/mariadb/jdbc/internal/stream/PacketOutputStream.java
An outputstream should never throw NPE even if it been invoked after it closed.
if no closed flag protection, when call PacketOutputStream again after it closed, it will throw NPE, not IOException.
=> OutputStream should never throw NPE

src/main/java/org/mariadb/jdbc/AbstractMariaDbPrepareStatement.java, src/test/java/org/mariadb/jdbc/PreparedStatementTest.java
Previously the `longValue` was used, which was incompatible with the MySQL Connector/J, and also meant that floating point numbers would lose their fractional part. This commit creates a new `BigDecimal` from the `doubleValue` instead.
=> Use the doubleValue of non-BigDecimal Number arguments to setObject.

src/main/java/org/mariadb/jdbc/MariaDbClientPreparedStatement.java, src/main/java/org/mariadb/jdbc/MariaDbServerPreparedStatement.java, src/main/java/org/mariadb/jdbc/MariaDbStatement.java, src/main/java/org/mariadb/jdbc/internal/util/scheduler/DynamicSizedSchedulerImpl.java, src/main/java/org/mariadb/jdbc/internal/util/scheduler/DynamicSizedSchedulerInterface.java, src/main/java/org/mariadb/jdbc/internal/util/scheduler/FixedSizedSchedulerImpl.java, src/main/java/org/mariadb/jdbc/internal/util/scheduler/MariaDbThreadFactory.java, src/main/java/org/mariadb/jdbc/internal/util/scheduler/SchedulerServiceProviderHolder.java
It is probably easier to digest through the commit's, but I figured I would include it all in a single PR.  Feel free to make requests for individual commit adjustments (or removals).
https://github.com/MariaDB/mariadb-connector-j/commit/46c4166b3d8072f5027d9658bc7af4134a842792
This commit is address an issue @rusher pointed me to with tomcat struggling to shutdown.  His recommendation was to track the connections and unscheduled the tasks as needed, and reschedule if we end up creating new connections.
I took a different angle to this.  We have not run into these issues, and I suspect it's because we are using https://github.com/threadly/threadly/ under the hood which defaults to daemon threads.  I am not aware of anything that we would need to hold the app shutdown up for, so it seems …
=> Pool improvements

documentation/Developers-Guide.md, src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java, src/test/java/org/mariadb/jdbc/DatabaseMetadataTest.java
DatabaseMetaData.getTables() typically returns for  "TABLE TYPES":
"TABLE", "VIEW", "SYSTEM TABLE", "GLOBAL TEMPORARY", "LOCAL TEMPORARY",
"ALIAS", "SYNONYM".
MySQL returns "BASE TABLE" as type for "TABLE" which is noted in MariaDbDatabaseMetaData.mapTableTypes()
Many applications / ORMs expect "TABLE" returned instead of "BASE TABLE"
A test has been added to test for this.
There is also a small correction in the documentation
=> DatabaseMetaData.getTables() returned "BASE TABLE" as TABLE TYPE

src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java
Old MySQL doesn't correctly parse "SELECT CONCAT ('a', 'b'); /* extra space after CONCAT */" query. Please, remove space after "CONCAT" function, use "CONCAT(...)" instead. Doesn't affect newer versions od MariaDB and/or MySQL.
=> Fixed compatibility issue with old MySQL database (5.0.77)

src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java
In CONJ-218 (change 4e8c7153e6a7f25128753f2b6527846013e24136), a table type of "BASE TABLE" is translated to "TABLE". The JDBC documentation describes "TABLE" as typical, so that's reasonable.
getTableTypes() returns the set of possible values for table types to be passed as a parameter to getTables() and to be expected in the results from getTables(). It should be modified to match, i.e. it should produce a value of "TABLE" and not "BASE TABLE".
=> getTableTypes() returns "TABLE" consistent with getTables()

MariaDbDatabaseMetaData.java, MariaDbDatabaseMetaDataTest.java, mariadb-java-client.iml, src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java, src/test/java/org/mariadb/jdbc/MariaDbDatabaseMetaDataTest.java
The method columnTypeClause has been modified to use the tinyInt1isBit flag. This makes sure things such as hibernate validation don't fail. It's solved by checking if the tinyInt1isBit flag is true and when it is true it will add an if to the sql each time the columnName is used to replace any occurences of 'tinyint(1)' with 'BIT'. If the flag is false the columnName will be added unmodified. This has been tested with an application using hibernate-validator-5.2.4.Final and MariaDB 10.1.2
=> CONJ-412: tinyInt1isBit is not applied in method columnTypeClause

src/main/java/org/mariadb/jdbc/internal/protocol/tls/MariaDbX509TrustManager.java
Removing 8 characters in the case of a file path that starts with 'file:///' removes the leading slash. This causes an error as the connector will assume you have provided a relative file path.
=> Retain leading slash when trust store beings with 'file:///'

src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java
Proposed fix for issue https://jira.mariadb.org/browse/CONJ-455
Please note that this is my first pull request for a fix so do double check it doesn't crash anything.
(I'm contributing the code of this whole pull request under the BSD-new license.)
=> ignore UNSIGNED mark in TINYINT(1) columns when TINYINT1_IS_BIT is set

src/main/java/org/mariadb/jdbc/MariaXaResource.java, src/main/java/org/mariadb/jdbc/internal/util/Utils.java
This fixed issue CONJ-489.
Caused by: javax.transaction.xa.XAException: (conn:41252) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '0x
at org.mariadb.jdbc.MariaXaResource.mapXaException(MariaXaResource.java:123)
at org.mariadb.jdbc.MariaXaResource.execute(MariaXaResource.java:137)
at org.mariadb.jdbc.MariaXaResource.start(MariaXaResource.java:314)
at com.atomikos.datasource.xa.XAResourceTransaction.resume(XAResourceTransaction.java:297)
The hexdump implementation is creating an XA statement as followed:
XA PREPARE  0x 31 39 32 2E 31 36 38 2E  32 35 31 2E 32 2E 74 6D     192.168.251.2.tm
31 34 39 36 36 30 31 31  37 38 38 32 35 30 32 35     1496601178825025
34 31 …
=> * fixed issue #CONJ-489

src/main/java/org/mariadb/jdbc/internal/io/output/AbstractPacketOutputStream.java
Length should still be length; as you'll otherwise lose data.
=> Proposed fix for CONJ-497

src/main/java/org/mariadb/jdbc/internal/com/read/resultset/SelectResultSet.java, src/test/java/org/mariadb/jdbc/DriverTest.java, src/test/java/org/mariadb/jdbc/ResultSetTest.java
This PR changes the behavior of `resultSet.relative()` when crossing result set boundaries in order to conform to the `java.sql.ResultSet#relative` javadoc.
One existing test, `DriverTest#testResultSetPositions`, had to be altered because it relied on an incorrect behavior (expected `relative(-1)` from the first row to not change the position).
=> CONJ-541 resultSet.relative() behavior is incorrect when crossing result set boundaries

documentation/plugin/GSSAPI.creole
404 error when click to README : https://github.com/MariaDB/server/blob/10.2/plugin/auth_gssapi/README.md
=> Update GSSAPI.creole 404 link 

src/test/java/org/mariadb/jdbc/CallStatementTest.java
Testing that stmt.getMoreResults() returns false fails with the current version showing that there's a bug which causes us some problems.
I created a JIRA bug report CONJ-542 for this.
=> Check that getMoreResults returns false

pom.xml
Currently, within an OSGi environment (such as apache karaf e.g.), when logging is requested through configuration, enabling it will fail inside LoggerFactory with "Logging cannot be activated, missing slf4j dependency" always.
This is due to the fact that the OSGi Metadata you already generate is incorrect/missing something.
This commit fixes this "Import-Package" statement by adding the org.slf4j package as an optional import package.
Please consider adopting this (rather simple) fix and release a bugfix because right now we use a locally "fixed" version instead of the official one.
=> Fix enabling logging in an OSGi environment

src/main/java/org/mariadb/jdbc/internal/protocol/AbstractConnectProtocol.java, src/main/java/org/mariadb/jdbc/internal/util/DefaultOptions.java, src/main/java/org/mariadb/jdbc/internal/util/Options.java
Adds support for the useAffectedRows JDBC URL parameter.
This is important for anyone who needs to run `UPDATE` statements and know, afterward, whether anything changed. (As opposed to learning only how many rows were matched.)
**Travis test:** https://travis-ci.org/dcposch/mariadb-connector-j/builds/335880775
I've tested functionality locally. Let me know if there's an easy way to add an integration test.
@rusher
=> [CONJ-384] support useAffectedRows

src/main/java/org/mariadb/jdbc/MariaDbPoolDataSource.java
//Sample Program to create NullPointerException:
public class ConnectionUsingDS {
public static void main(String args[]) throws SQLException {
MariaDbPoolDataSource pool =
new MariaDbPoolDataSource("jdbc:mariadb://localhost/testj?user=root&maxPoolSize=10");
try (Connection conn = pool.getConnection()) {
try(Statement stmt = conn.createStatement()){
ResultSet rs = stmt.executeQuery("select 'Hello World!'");
while(rs.next()){
System.out.println(rs.getString(1));
}
System.out.println(pool.getDatabaseName() +", "+pool.getPort());
}
}
}
}
//Output: 
//Hello World!
//Exception in thread "main" java.lang.NullPointerException
//	at org.mariadb.jdbc.MariaDbPoolDataSource.getPort(MariaDbPoolDataSource.java:153)
//	at mariadb.test.connection.ConnectionUsingDS.main(ConnectionUsingDS.java:32)
=> NPE fix if url used like: jdbc:mariadb://localhost/testj?user=root&maxPoolSize=10

src/main/java/org/mariadb/jdbc/internal/util/exceptions/ExceptionMapper.java
- 1213 ER_LOCK_DEADLOCK was not considered to run 'SHOW ENGINE INNODB STATUS'. In this case, lock/deadlock information is also required when corresponding option is enabled from a client-side (includeInnodbStatusInDeadlockExceptions=true)
=> [misc] enabled running  of 'SHOW ENGINE INNODB STATUS' for error code 1213

src/test/java/org/mariadb/jdbc/BaseTest.java
Hi,
In MariaDB Connector J tests, there is a condition to check whether the max_allowed_packet is greater than certain value, and the previous logic is as follows:
max_allowed_packet > value && innodb_log_file_size > 10*value.
Then for actual test, when max_allowed_packet > value and innodb_log_file_size < 10*value on server, it will regard it as max_allowed_packet < value, and certain test will fail, e.g. send40mSqlCompressDataException.
I think this is unreasonable for test itself, and the condition to check innodb_log_file_size should be removed.
Can you help review the change for it and give your comment and approval?
Thanks & Best Regards,
Qianqian Bu
=> Remove the check of innodb_log_file_size condition when decide checkMaxAllowedPacketMoreXXm in BaseTest.Java

src/test/java/org/mariadb/jdbc/BaseTest.java
In the test suite, there is a system property runLongTest, it used the wrong method Boolean.getBoolean to parse it which resulted the value of runLongTest was always false. Should use Boolean.parseBoolean instead.
=> runLongTest system property does not work as expected

src/test/java/org/mariadb/jdbc/StatementTest.java
There are three tests:
StatementTest#testLoadDataInvalidColumn and 
LocalInfileInputStreamTest#testLocalInfileUnValidInterceptor
if the first test is ran before the second test cases, the second test case will fail for sure. 
The reason is that 
StatementTest#testLoadDataInvalidColumn  will set AbstractQueryProtocol::localInfileInputStream field but never clear it.
LocalInfileInputStreamTest#testLocalInfileUnValidInterceptor will use AbstractQueryProtocol::readLocalInfilePacket  in which its logic depends on whether AbstractQueryProtocol::localInfileInputStream is null or not to do following work and decide what to write to table.  Since AbstractQueryProtocol::localInfileInputStream is not cleaned in previous test StatementTest#testLoadDataInvalidColumn, it will use the value and try to …
=> Should clear AbstractQueryProtocol::localInfileInputStream field after set MariaDbStatement.setLocalInfileInputStream if throw exception

src/main/java/org/mariadb/jdbc/internal/com/read/dao/CmdInformationBatch.java
Improvement of https://jira.mariadb.org/browse/CONJ-384
If update of rewritten batch return "no changes" batch return array of "no changes". Otherwise it works as before.
- tested it with our project.  
- test "updateCounts.size() == 1" may be unnecessary
=> [CONJ-712] RewriteBatchedStatements and useAffectedRows should report no changes correctly

CONTRIBUTING.md, pom.xml, src/main/java/org/mariadb/jdbc/internal/osgi/MariaDbActivator.java, src/main/java/org/mariadb/jdbc/internal/osgi/MariaDbDataSourceFactory.java
Currently users are enforced to write their own code or using third party wrappers to use MariaDB together with OSGi JDBC/JPA Service,
This PR adds support for the [OSGi Data Service Specification for JDBC™ Technology](https://osgi.org/specification/osgi.cmpn/7.0.0/service.jdbc.html)
This allows users of OSGi to use the MariaDB driver in a generic fashion. This is also a perquisite for using MariaDB together with the OSGi JPA Specification.
Since this part of the code is only activated inside an OSGi-Framework for all other users this change is completely transparent.
=> [OSGi] Support the Data Service Specification for JDBC™ Technology

documentation/failover-and-high-availability-with-mariadb-connector-j.creole
I reported a bug because the `createDatabaseIfNotExist` setting causes reader instances to be silently blacklisted. You can find the bug report at [CONJ-769](https://jira.mariadb.org/browse/CONJ-769).
This commit adds a sentence about this argument to the section about Aurora specific configuration options.
=> [CONJ-769] Add a hint about createDatabaseIfNotExist

src/main/java/org/mariadb/jdbc/internal/util/pool/Pools.java
When a pool is closed, it closes and nulls a global executor used by all pools. In some cases, this occurs even if there are still other pools open. Closing pools when the executor is nulled results in an exception:
```
java.lang.NullPointerException: null
at org.mariadb.jdbc.internal.util.pool.Pools.shutdownExecutor(Pools.java:122)
at org.mariadb.jdbc.internal.util.pool.Pools.remove(Pools.java:72)
at org.mariadb.jdbc.internal.util.pool.Pool.close(Pool.java:470)
at org.mariadb.jdbc.MariaDbPoolDataSource.close(MariaDbPoolDataSource.java:621)
```
I have fixed the problem by ensuring the map of pools is checked for emptiness in all cases.
=> Fix pool.close() issue

src/main/java/org/mariadb/jdbc/authentication/AuthenticationPluginLoader.java, src/main/java/org/mariadb/jdbc/credential/CredentialPluginLoader.java
For conj-742, Squirrel Client reports " Client does not support authentication protocol requested by server. plugin type was = 'xxx' "
This problem was fixed in commit 4e0705bb306a5f7efef222c6886e3a561b13ab60.
But after this commit changed the loader into static, it reports Access denied problem (stack as at bottom). And this problem as been reported on conj-807.
I've tested that for conj-742, there is only need to specify the class loader Driver.class.getClassLoader() to solve the Squirrel Client problem. So I proposed this fix to solve both conj-742 and conj-807.
Thread 35 got Exception: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=xx)(port=3306)(type=master) : Access denied for user 'xx'@'xx' (using password: YES) …
=> for-CONJ-742-and-CONJ-807, static loader for AuthenticationPlugin introduces Access Denied problem

src/main/java/org/mariadb/jdbc/internal/util/Utils.java
In my project, I have a class that extends ConfigurableSocketFactory, but the setConfiguration method is never called. I added a breakpoint to if (socketFactoryClass.isInstance(ConfigurableSocketFactory.class)) {, and the expression was evaluating to false.
From my googling, I landed at https://stackoverflow.com/questions/31083699/java-class-isinstance-always-returns-false, which indicated that the evaluation was being done backwards.
When I evaluated ConfigurableSocketFactory.class.isInstance(socketFactory), the result was true
=> Fix - setConfiguration not being called on classes that extend ConfigurableSocketFactory

src/main/java/org/mariadb/jdbc/internal/com/read/resultset/rowprotocol/TextRowProtocol.java, src/test/java/org/mariadb/jdbc/StringUTFTest.java
Detected at one of my clients.
They use polish special characters like ść
The length in TextRowProtocol is set to 2 for each of those characters so 4 in our example.
With this the current code 
`return new String(buf, pos, Math.min(maxFieldSize * 3, length), StandardCharsets.UTF_8)
.substring(0, Math.min(maxFieldSize, length));`
results into an ArrayOutOfBoundsError at the  substring call.
I added a test case and a quick fix for it.
Travis fails on environment issues. Nothing to do with my change.
=> [CONJ-805] >1Byte UTF8 character issue if maxFieldSize is set

pom.xml
The import package declarations seem to be necessary in an osgi environment, tested with karaf 4.x.x
=> added osgi related packege imports for gss

src/test/java/org/mariadb/jdbc/CredentialPluginTest.java
When test comes to after section, the user must already exist. And this syntax is not supported by MySQL5.6. So I think the if exists condition can be safely removed.
=> user must exist and 5.6 does not support the syntax if exists

src/main/java/org/mariadb/jdbc/HostAddress.java, src/main/java/org/mariadb/jdbc/internal/failover/impl/AuroraListener.java
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html#Aurora.Overview.Endpoints.Types
There are three Aurora endpoints: cluster endpoint, reader endpoint, and custom endpoint.
But it didn't support custom endpoint.
This PR corresponds to the URL format of the custom endpoint.
Please let me know if there is anything else to do
=> Added support for Aurora cluster custom endpoints

src/main/java/org/mariadb/jdbc/MariaDbDatabaseMetaData.java
From test, mysql 8.0 still does not have IS_GENERATED column. So the condition should not include 8.0.
Tested version: 8.0.15
=> mysql 8.0 still does not have IS_GENERATED column

src/main/java/org/mariadb/jdbc/internal/util/pool/Pool.java
The commit here fixes the issue noted in https://jira.mariadb.org/browse/CONJ-885 where if a `SQLException` occurs while adding a new connection to the pool, then that exception is never reported/logged which can then make it difficult to understand subsequent failures to obtain connection(s) from the `Pool` instance.
=> CONJ-885 Log any SQLException that occurs while adding connections to pool

README.md, src/main/java/org/mariadb/jdbc/MariaDbConnection.java
Unnecessary memory allocations are done when switching auto commit.
It can be avoided by compiling both variants in.
=> Avoid creating new strings when switching auto-commit.

src/main/java/org/mariadb/jdbc/internal/protocol/AbstractConnectProtocol.java, src/main/java/org/mariadb/jdbc/internal/protocol/AbstractQueryProtocol.java, src/main/java/org/mariadb/jdbc/internal/util/pool/Pool.java
As noted in https://jira.mariadb.org/browse/CONJ-897, the commit in this PR enhances certain log messages to print out the connection id. This change helped us in a big way to narrow down the issue noted in https://jira.mariadb.org/browse/CONJ-896.
=> CONJ-897 Include connection id in certain important log messages

pom.xml
In light of the recent news related to Log4j, Logback fixed a security vulnerability in 1.3.0-alpha11. More info at http://mailman.qos.ch/pipermail/logback-user/2021-December/005168.html
=> Upgrading Logback 1.3.0-alpha11

bnd.bnd, pom.xml
Added the OSGi metadata using the bnd-maven-plugin. The resultant jar is an OSGi bundle now and deploys correctly to OSGi runtime.
=> Fix for https://jira.mariadb.org/browse/CONJ-925

src/main/java/org/mariadb/jdbc/util/VersionFactory.java, src/test/java/org/mariadb/jdbc/unit/util/VersionFactoryTest.java
Prevent loading properties from 'mariadb.properties' if the file is not found.
Without this commit, a Null Pointer Exception is thrown when `org.mariadb.jdbc.util.VersionFactory.getInstance()` is called and the properties file is missing.
With this commit, the Version will fallback to the `tmpVersion` of "5.5.0", which looks to be the intended behavior of this class.
=> Prevent NPE on missing properties

src/main/java/org/mariadb/jdbc/Statement.java, src/test/java/org/mariadb/jdbc/integration/StatementTest.java
Straight port (give or take a few necessary cosmetics) of Statement.enquote* methods from 2.x branch.
=> [CONJ-1058] port Statement.enquote* methods from connector 2.x

src/main/java/org/mariadb/jdbc/internal/io/output/CompressPacketOutputStream.java
Avoid increasing the sequence of sub header twice during flushing the compressed packet.
=> [CONJ-1145]Wrong sequence number of sub header with compressing procotol active

src/test/java/org/mariadb/jdbc/integration/ErrorTest.java
Port 3000 is not that uncommon of a port for a MariaDB instance to run on. To avoid conflicting with setups where there actually is a MariaDB instance running on that port, use a port that is near the end of the ephemeral range. Hopefully this is something that is less likely to conflict.
=> Use 32760 as the "unused" port number

pom.xml
License name in pom.xml is recommended to be valid SPDX license id.
=> Correct license id in pom.xml to LGPL-2.1-or-later

src/main/java9/module-info.java
The waffle-jna dependency is needed only when Windows GSSAPI authentication is used. In a previous commit, the `static` was incorrectly removed, making the dependency a hard requirement when running on JPMS.
https://github.com/mariadb-corporation/mariadb-connector-j/commit/5ac67b2d17dcf4e0272781426d67299dedf5a377
However, maven is not the same as JPMS. An optional dependency via Maven *is not* the same as `requires static` in JPMS. They serve entirely different purposes. By removing `requires static`, you are saying that all deployments *must* have waffle-jna present on the module path.
Re-adding `requires static` will not affect existing clients using MariaDB Connector-J. If they used waffla-jna before, they will continue to use it after this change. …
=> [CONJ-1053] Make the JPMS requirement on waffle-jna static

pom.xml
Dependency `com.github.waffle:waffle-jna` 3.3.0 pulls `com.github.ben-manes.caffeine:caffeine` 2.9.3 which is the last version in the 2.x release train from December 2021. As many other libraries rely on the 3.x release train, this can lead to conflicting transitive  dependencies. Waffle 3.4.0 already is on caffeine 3.x but I thought going with the latest version 3.5.0 is sufficient.
=> Bump `com.github.waffle:waffle-jna` from 3.3.0 to 3.5.0

src/test/java/org/mariadb/jdbc/integration/Common.java, src/test/java/org/mariadb/jdbc/integration/RedirectionTest.java
The redirection test now checks for the MaxScale version before proceeding.
This will make it work with 23.02 and older
releases of MaxScale.
=> Check MaxScale version

src/main/java/org/mariadb/jdbc/Configuration.java, src/test/java/org/mariadb/jdbc/unit/util/ConfigurationTest.java
This Pull Request is intend to fix flakiness in the following tests in [org.mariadb.jdbc.unit.util.ConfigurationTest](https://github.com/mariadb-corporation/mariadb-connector-j/blob/9c2db3bee043c71755a35ace70fde10c8fffa6a9/src/test/java/org/mariadb/jdbc/unit/util/ConfigurationTest.java#L20)
1. [org.mariadb.jdbc.unit.util.ConfigurationTest#testBuild](https://github.com/mariadb-corporation/mariadb-connector-j/blob/9c2db3bee043c71755a35ace70fde10c8fffa6a9/src/test/java/org/mariadb/jdbc/unit/util/ConfigurationTest.java#L81)
2. [org.mariadb.jdbc.unit.util.ConfigurationTest#builder](https://github.com/mariadb-corporation/mariadb-connector-j/blob/9c2db3bee043c71755a35ace70fde10c8fffa6a9/src/test/java/org/mariadb/jdbc/unit/util/ConfigurationTest.java#L869)
3. …
=> Fixing flaky configuration tests

src/main/java/org/mariadb/jdbc/client/column/UnsignedIntColumn.java, src/main/java/org/mariadb/jdbc/client/column/UnsignedSmallIntColumn.java, src/main/java/org/mariadb/jdbc/client/column/UnsignedTinyIntColumn.java, src/test/java/org/mariadb/jdbc/integration/codec/IntCodecTest.java, src/test/java/org/mariadb/jdbc/integration/codec/SmallIntCodecTest.java, src/test/java/org/mariadb/jdbc/integration/codec/TinyIntCodecTest.java, src/test/java/org/mariadb/jdbc/integration/resultset/ResultSetMetadataTest.java
1.The pr aims to fix unsigned jdbc types, include:
- UnsignedIntColumn from `Types.BIGINT` to `Types.INTEGER`
- UnsignedSmallIntColumn from `Types.INTEGER` to `Types.SMALLINT`
- UnsignedTinyIntColumn from `Types.SMALLINT` to `Types.TINYINT`
2.why?
When we recently migrated `mariadb-connector-j` from `2.x` to `3.x` in Spark and used `mariadb-connector-j` to access `MySQL` data, We found that 'java. sql.Types' returned by some `unsigned` jdbc types of '2.x ' and ' 3.x ' are inconsistent, as follows:
|Column Type Define|2.x|3.x|
|---|---|---|
|TINYINT UNSIGNED|Types.TINYINT|Types.SMALLINT|
|SMALLINT UNSIGNE|Types.SMALLINT|Types.INTEGER|
|INT UNSIGNED|Types.INTEGER|Types.BIGINT|
```scala
val dataType = resultSetMetaData.getColumnType(i)
```
3.The `data type` is generally determined by two …
=> Fix unsigned jdbc types

src/main/java/org/mariadb/jdbc/pool/Pool.java, src/main/java/org/mariadb/jdbc/pool/Pools.java, src/test/java/org/mariadb/jdbc/integration/PoolDataSourceTest.java
Initializing multiple pools in parallel incurred significant lock contention on `poolMap` because this lock was held while any `Pool` was being constructed (which could take several seconds).
Because of this, connecting to independent databases in parallel was not possible (Pool creation was serialized), severely limiting overall performance.
* Add `PoolHolder` to defer creation of `Pool` and act as a lock for each pool key.
* Insert a new `PoolHolder` while holding the `poolMap` lock, reducing global thread contention.
* Threads looking up the same key will acquire the same `PoolHolder` and that `PoolHolder` will ensure that only one `Pool` is created. Threads looking up unrelated `PoolHolder` will not be blocked by `Pool` creation.
* Make registerJxm/unRegisterJmx thread safe. When Pool …
=> Speed up concurrent pool creation

README.md
since CI is now using github action, use according badge on README page
=> [misc] add correct CI badge
